name = "bottles-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "bottlesMeta"
id = "${CF_KV_NAMESPACE_ID}"

[[r2_buckets]]
binding = "R2"
bucket_name = "${CF_R2_BUCKET_NAME}"
